# ==============================================================================
# MOST IMPORTANT CONFIGURATION BLOCK
# Edit values here. They are injected into the services below using YAML aliases.
# ==============================================================================
x-config:
  puid: &puid 1000
  pgid: &pgid 1000
  tz: &tz "Europe/London"
  public_url: &public_url "http://please-define-public-accessible-addon-server-url"
  qbit_user: &qbit_user "admin"
  qbit_pass: &qbit_pass "get_from_qbittorrent_first_boot_logs"
  jackett_api_key: &jackett_api_key "get_from_jackett_first_webui_access"
# ==============================================================================


# ==============================================================================
# You probably wan't to either enable the port mappings below or set up a 
# reverse proxy to access the services from outside the docker network.
# ==============================================================================

services:
  jackett:
    image: lscr.io/linuxserver/jackett:0.24.1392
    environment:
      PUID: *puid
      PGID: *pgid
      TZ: *tz
    volumes:
      - mini_media_server_jackett_data:/config
      # - /path/to/blackhole:/downloads
    # ports:
    #   - "9117:9117"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    environment:
      PUID: *puid
      PGID: *pgid
      TZ: *tz
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - mini_media_server_qbittorrent_data:/config
      # Mount the shared media_downloads volume to /downloads (read-write)
      - mini_media_server_downloads:/downloads
    # ports:
    #   - "8080:8080"
    #   - "6881:6881"
    #   - "6881:6881/udp"
    restart: unless-stopped

  addon-server:
    image: ghcr.io/josias-r/mini-media-server-addon:0.0.4
    environment:
      PORT: 7000
      PUBLIC_URL: *public_url
      QBITTORRENT_URL: "http://qbittorrent:8080"
      QBITTORRENT_USERNAME: *qbit_user
      QBITTORRENT_PASSWORD: *qbit_pass
      JACKETT_URL: "http://jackett:9117"
      JACKETT_API_KEY: *jackett_api_key
      # whether torznab strict query is used (must be supported by the indexer used) or a text search (more flexible, but less accurate)
      JACKETT_SEARCH_TYPE: "text" # 'imdb' or 'text'
      DOWNLOAD_PATH: "/downloads"
    volumes:
      # Mount the same media_downloads volume to /downloads, but read-only!
      - mini_media_server_downloads:/downloads:ro
      # UNUSED ATM - WILL BE USED TO PERSIST RUNTIME CONFIGS-SIMPEL DATA SOON
      - mini_media_server_addon_data:/app/data
    # ports:
    #   - "7000:7000"
    restart: unless-stopped
    depends_on:
      - jackett
      - qbittorrent

volumes:
  mini_media_server_jackett_data:
  mini_media_server_qbittorrent_data:
  # UNUSED ATM - WILL BE USED TO PERSIST RUNTIME CONFIGS-SIMPEL DATA SOON
  mini_media_server_addon_data:
  # example with external mounted hdd
  mini_media_server_downloads:
    driver: local
    driver_opts:
      type: none
      device: /mnt/ext_hdd/mini-media-server/downloads
      o: bind
